### ISSUE TITLE
Distinguish between success and failure in `Close` message

### ISSUE THREAD

**Issue by phoebe-lew** [TBD54566975/tbdex#242] opened 2024-02-20 21:06 UTC
> can we provide a boolean property on the Close message indicating if the transaction was completed successfully or not. As a wallet app, all I get is Close and some String reason (again that could be in another language). I may want to add conditional logic to my app to display certain flows based on if the transaction completed successfully or not, and right now that's not possible without trying to programmatically decipher the Close.reason and determine if this String means things are good or not. 

from @angiejones

**Comment by diehuxx** [comment] 2024-02-26 22:46
I would argue a `Close` is always "bad". To know if an exchange is successful we use `OrderStatus`, not `Close`. Currently, in `tbdex-js`, `tbdex-kt`, and the spec, an exchange is terminal either with `Close` or `OrderStatus` where `Close` indicates a premature termination. In the existing implementations, after an `OrderStatus`, you actually cannot add a `Close` message.

From [the spec section for `Close`](https://github.com/TBD54566975/tbdex/tree/9a9ed69/specs/protocol#close):
> > Alice -> PFI: "Not interested anymore." or "oops sent by accident"
>
> > PFI -> Alice: "Can't fulfill what you sent me for whatever reason (e.g. RFQ is erroneous, don't have enough liquidity etc.)" or "Your exchange is completed"
>
> a Close can be sent by Alice or the PFI as a reply to an RFQ or a Quote. It indicates a terminal state. No messages can be added to an exchange after a Close.

**Comment by angiejones** [comment] 2024-02-26 23:14
> I would argue a `Close` is always "bad". To know if an exchange is successful we use `OrderStatus`, not `Close`. Currently, in `tbdex-js`, `tbdex-kt`, and the spec, an exchange is terminal either with `Close` or `OrderStatus` where `Close` indicates a premature termination. In the existing implementations, after an `OrderStatus`, you actually cannot add a `Close` message.
> 
> From [the spec section for `Close`](https://github.com/TBD54566975/tbdex/tree/9a9ed69/specs/protocol#close):
> 
> > > Alice -> PFI: "Not interested anymore." or "oops sent by accident"
> > 
> > 
> > > PFI -> Alice: "Can't fulfill what you sent me for whatever reason (e.g. RFQ is erroneous, don't have enough liquidity etc.)" or "Your exchange is completed"
> > 
> > 
> > a Close can be sent by Alice or the PFI as a reply to an RFQ or a Quote. It indicates a terminal state. No messages can be added to an exchange after a Close.

But there are multiple OrderStatus messages and who knows what the text of the message will be. This isn't better than using `Close` to try to decipher if the transaction completed successfully or not. A PFI can indicate "ok", "good", "done", "bueno", "1", ANYTHING. The request is for a boolean field so nothing is lost in translation and wallet apps don't need to look up every PFI's messaging scheme to figure out how to handle the end state of transactions

**Comment by phoebe-lew** [comment] 2024-02-27 12:25
@diehuxx 
> In the existing implementations, after an OrderStatus, you actually cannot add a Close message.

This should not be the case...we're currently using `Close` as equivalent to "complete" as well, so the client knows to stop polling. Close does not necessarily mean premature termination or error. Alice saying she isn't interested in the quote is terminal but not erroneous.

**Comment by angiejones** [comment] 2024-02-27 14:01
> @diehuxx
> 
> > In the existing implementations, after an OrderStatus, you actually cannot add a Close message.
> 
> This should not be the case...we're currently using `Close` as equivalent to "complete" as well, so the client knows to stop polling. Close does not necessarily mean premature termination or error. Alice saying she isn't interested in the quote is terminal but not erroneous.

Yes, correct. @diehuxx we tell customer agents to continue polling until a Close message has been written to the exchange

<img width="833" alt="image" src="https://github.com/TBD54566975/tbdex/assets/15972783/073ad587-42fc-48c7-8513-53a88b0f820a">

**Comment by angiejones** [comment] 2024-02-27 21:33
@diehuxx `Close` is the terminal message, I think we should keep it that way. Adding `Close.data.success` as a boolean field would solve the issue.

**Comment by diehuxx** [comment] 2024-03-01 18:32
> Close is the terminal message, I think we should keep it that way.

@angiejones I looked at the spec again and it looks like `Close` is _a_ terminal message, but it is not _the only_ terminal message according to the spec and all existing implementations. `Close` is only allowed directly after an `RFQ` or a `Quote`. From [the spec](https://github.com/TBD54566975/tbdex/tree/9a9ed69/specs/protocol#close):
> a Close can be sent by Alice or the PFI as a reply to an RFQ or a Quote. It indicates a terminal state. No messages can be added to an exchange after a Close.

If you are interested in avoid breaking changes, we should avoid Proposal 1. Proposal 1 would constitute a breaking change in both message structure and the exchange state machine.

After some additional thought, I recommend an approach that combines aspects of Proposals 2 and 3

### Recommended Proposal: Add `state` enum to `OrderStatus`.
The existing exchange state machine seems sufficient. `Close` messages can terminate an exchange directly after an `RFQ` or a `Quote`. After an `Order`, there can be any number of `OrderStatus` messages.

To denote whether the payment was successful or not in an `OrderStatus`, we should add an optional field called `OrderStatus.data.state` which can have three values: `COMPLETE`, `PENDING`, and `TERMINATED`. We should rename the existing `OrderStatus.data.orderStatus` to `OrderStatus.data.detail`. It remains useful to have an unstructured string to contain additional information that is dependent on the type and context of the payment.

**Comment by angiejones** [comment] 2024-03-01 23:55
I dont think we need to overcomplicate this. Again "Adding Close.data.success as a boolean field" is a very simple solution that doesn't break the current implementation or message flow

**Comment by diehuxx** [comment] 2024-03-02 02:11
Adding the field to `Close` does not break the message flow but altering the meaning of `Close` to be required at the end of all message flows to denote success does break the message flow. If the spec does not currently contradict that setup, then it is at least ambiguous and the implementations fail to reflect that setup. It's not overcomplicating it to consider the how TBDex will be used.

In addition to the broader questions I raised in my previous comment (payment reversal, whether "closing" successful exchanges is necessary or desirable), we also need to address the details of adding a success boolean to `Close`. Is the boolean optional? When is it required? Does `false` mean something different than absent? If an RFQ is followed by a `Close` with `success == true` what does that mean?

**Comment by angiejones** [comment] 2024-03-02 02:18
> Adding the field to `Close` does not break the message flow but altering the meaning of `Close` to be required at the end of all message flows to denote success does break the message flow. If the spec does not currently contradict that setup, then it is at least ambiguous and the implementations fail to reflect that setup. It's not overcomplicating it to consider the how TBDex will be used.
> 
> In addition to the broader questions I raised in my previous comment (payment reversal, whether "closing" successful exchanges is necessary or desirable), we also need to address the details of adding a success boolean to `Close`. Is the boolean optional? When is it required? Does `false` mean something different than absent? If an RFQ is followed by a `Close` with `success == true` what does that mean?

Ah, I see your point. I have always viewed Close as the single final message of an exchange. Let me read everything again, including the spec, and come back...

**Comment by angiejones** [comment] 2024-03-02 19:33
ok I read everything again. I don't see a different interpretation of "Close is the final message of the exchange". 

> a Close can be sent by Alice or the PFI as a reply to an RFQ or a Quote. It indicates a terminal state. No messages can be added to an exchange after a Close.

I assume even if no Order is ever placed, once the Quote expires, a Close message will be sent. I'll ask Frank and Moe to weigh in so that we're all on the same page (even without the proposed 'success' flag)

**Comment by KendallWeihe** [comment] 2024-03-04 14:14
Hey hey all, just catching up to this, apologies, I would've weighed in earlier had I known about it

I just spent some time trying to dig through history to find the references to what I'm about to say, but I was unsuccessful ☹️ Nevertheless, so the original intent of `Close` and `OrderStatus` was as followed. `Close` is a terminal state which is non-successful, and `OrderStatus` is a status of a given `Order`, one-or-more of which may be considered terminal. I originally advocated `Close` to be called `Cancel` or `Reject`.

Granted, the spec may not reflect what I have said here, and/or these semantic definitions may have evolved since I last touched this subject. Nevertheless, we have a problem to be solved here in the current moment, and solve it we shall!

I'm hesitant to vote for the proposal here (@angiejones in your comment above):

> Adding Close.data.success as a boolean field would solve the issue

Because it's a slight conflation between the two semantic use cases. In an abstract sense, we need one message type which will deterministically terminate the exchange during a premature phase, and then we also need a separate message type which is an application-defined generic space to represent the state of the given `Order`. Venturing into the use case of chargebacks is actually relevant here. Because, what does it mean for a financial exchange to be "final"? It's different depending on the given financial rails being used; Bitcoin transactions are irreversible, but a credit card payment is not. Ultimately it's a matter of jurisdictional legalese. And so through that lens, there cannot be a protocol-prescribed standard of finality, because it's not something the protocol can enforce. That said, prematurely terminating an exchange is a state of finality which is standard across all payment mechanisms. Which is to say, all exchanges, no matter the medium, can be terminated prior to an agreed-upon execution (that is, the `Order` message is the state change in which the exchange transforms from being able to be terminated prematurely to being in the amorphous phase of finality).

Alright, a lot of words, I'm sorry, payments are difficult.

The next thing I would say to the above is, "but Kendall, sure there is no standard state of finality, but every transaction, even those which are reversible, does enter a state wherein it's considered to be successful and we can all go about our lives, albeit in some mediums that state can be reversed, the state still exists in standard!" So, I'll put forth two possible proposals (either or, but not both):

1. We introduce a well-defined set of `OrderStatus` values into the spec. One of which may be something like `SUBJECTIVELY_SUCCESSFUL`. This set of status' may or may not be strictly required, let's debate. Either they're "recommended" or they're "required." Either way, regardless of it they're required or not, the spec must make clear that the `OrderStatus` set of potential status' can be extended to more than just what's defined here.
2. We consider an abstraction layer on top of tbdex here, wherein we have specifications unique to given payment mediums (blockchains, credit cards, etc) where each is it's own specification with it's own well-defined set of status'.

**Comment by mistermoe** [comment] 2024-03-04 16:35
`Close` should be _the_ terminating message for tbdex exchanges. this is necessary given that there isn't a prescribed enumeration of order statuses by design. different PFIs will use different statuses based on their own backend systems. there _may_ emerge conventional statuses for specific currency pairs _but_ we're a long way from that. 

At the protocol level, I think it's a bad idea to worry about PFI specific state machines. Necessitating a `Close` at the end gives us a guaranteed way to know that an exchange is finished.

`Close.data.completed` feels redundant given that `Close` inherently means "completed", "finished" "done". I think `Close.data.success` makes more sense. Proposing that it be an _optional_ field where:
* not present == not applicable
* `false` == error occurred. look to `orderStatus` messages for more detail
* `true` == funds transfered

Examples:

```
Alice: RFQ
Alice: Close (whoops jk, don't send me a quote)
```

`Close.data.success` is not applicable here and therefore not present


---

```
Alice: RFQ
PFI: Quote
Alice: Order
PFI: OrderStatus x n
PFI: Close 
```

`Close.data.success` _is_ applicable here and therefore present. `true` would imply that funds were transferred etc. `false` would imply sad times. either way, the wallet now knows that it can stop polling _and_ what the outcome of the exchange is _without_ having to impossibly interpret different order statuses

---

Going to create a separate github issue to discuss all possible usages of `Close` so that we can be far more specific in the spec and in our guides.

**Comment by mistermoe** [comment] 2024-03-04 16:44
@KendallWeihe, we can discuss what you raised in that separate github issue.

**Comment by mistermoe** [comment] 2024-03-04 16:44
@angiejones 

> I assume even if no Order is ever placed, once the Quote expires, a Close message will be sent. I'll ask Frank and Moe to weigh in so that we're all on the same page (even without the proposed 'success' flag)


will raise in that separate github issue

**Comment by angiejones** [comment] 2024-03-04 18:30
> `Close` should be _the_ terminating message for tbdex exchanges. this is necessary given that there isn't a prescribed enumeration of order statuses by design. different PFIs will use different statuses based on their own backend systems. there _may_ emerge conventional statuses for specific currency pairs _but_ we're a long way from that.
> 
> At the protocol level, I think it's a bad idea to worry about PFI specific state machines. Necessitating a `Close` at the end gives us a guaranteed way to know that an exchange is finished.
> 
> `Close.data.completed` feels redundant given that `Close` inherently means "completed", "finished" "done". I think `Close.data.success` makes more sense. Proposing that it be an _optional_ field where:
> 
> * not present == not applicable
> * `false` == error occurred. look to `orderStatus` messages for more detail
> * `true` == funds transfered
> 
> Examples:
> 
> ```
> Alice: RFQ
> Alice: Close (whoops jk, don't send me a quote)
> ```
> 
> `Close.data.success` is not applicable here and therefore not present
> 
> ```
> Alice: RFQ
> PFI: Quote
> Alice: Order
> PFI: OrderStatus x n
> PFI: Close 
> ```
> 
> `Close.data.success` _is_ applicable here and therefore present. `true` would imply that funds were transferred etc. `false` would imply sad times. either way, the wallet now knows that it can stop polling _and_ what the outcome of the exchange is _without_ having to impossibly interpret different order statuses
> 
> Going to create a separate github issue to discuss all possible usages of `Close` so that we can be far more specific in the spec and in our guides.

This is perfect. Thank you, Moe!

**Comment by KendallWeihe** [comment] 2024-03-05 13:26
Do we allow `Close` after `Order` but before `OrderStatus`?

**Comment by diehuxx** [comment] 2024-03-05 19:13
> this would be new to me to hear that a reversible transaction is one single transaction which has been reversed, and that transactions don't typically have finality. my understanding is that transactions always have finality, and a reversal would happen as a separate, self-contained transaction (even if it looks to the customer like a given transaction was "reversed"). if we think of traditional ledgers, the original transaction doesn't get modified or erased, but rather followed up with a second transaction to show its reversal. so a reversal would be two transactions that zero out. but super interested to hear where you learned about this and to learn more about that approach!

@kirahsapong Reversibility exists in many many types of fiat payments. The traditional payments system does not have finality, or at least finality can take very long -- on the order of weeks or even months. Satoshi discusses some of the tradeoffs of reversibility in the Introduction to the bitcoin whitepaper. Reversibility is also discussed in [section 6.0.2 of the TBDex whitepaper](https://tbdex.io/whitepaper.pdf). Payment reversal is a significant risk that financial institutions take on when they process payments.

This is one reason why exchanging fiat for bitcoin is risky: Alice sends Bob bitcoin, Bob sends Alice dollars, Bob calls his bank to issue a chargeback, and now Alice is out of luck. There is trust inherent in the transaction. Alice must trust Bob and Bob's bank not to leave her emptyhanded. TBDex represents a trust layer that can facilitate decentralized exchange of fiat and crypto. In this case there are three "money movements": bitcoin payment, dollar payment, and dollar chargeback. But since Bob initiated both the dollar payment and chargeback, it is useful to think of that as a single transaction.

In a ledgering software services I have used, you're right that there are typically two database rows representing a money movement are present when a transaction is reversed. It is also common for those two rows to have the same `transaction_id` or even another table called `transactions` which both `money_movement` rows. Naturally different implementations of a ledger might use different terms or database schemas, but the concept applies to many of them.

**Comment by KendallWeihe** [comment] 2024-03-06 15:12
Lot's of killer discourse, but for the sake of implementation focus, summarizing the new features here:

- `Close` should always exist for all exchanges, it's the terminal message (as in, it always exist _at the end_)
- `Close` has a new property `success` of type boolean
- Logic could be understood as following

```
if Close.success == null then that means Close was sent prior-to the Order execution
else if Close.success == true then Close was sent after a successful Order execution
else if Close.success == false then Close was sent after a failed Order execution
```

With regards to how this state machine can drive wallet (GUI) experience, [see comment here](https://github.com/TBD54566975/tbdex/issues/256#issuecomment-1979741452)

TODO: unclear to me if `Close` is allowed after `Order` but before `OrderStatus`? @mistermoe @phoebe-lew @angiejones could you define the rule here?

**Closed** 2024-03-06 22:59 UTC
Labels: enhancement, protocol
